### ISSUE TITLE
White Screen when end install..

### ISSUE THREAD

**Issue by michalmw** [michaelkrone/generator-phalcon#3]
Hello,

i try install app in yo generator - and when end i have white screen on my localhost:2222 
/ but when i delete .htaccess and go to url localhost:2222/test.php (is my test phpinfo())

I see phalcon is included. Someone can help?

**Comment by michaelkrone** [comment]
Hi.

Could you provide some more information, e.g. are the templates generated correctly?

**Comment by michaelkrone** [comment]
Closing this now, please feel free to provide some more informations here and I will reopen.
